/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: {
          base: "rgb(var(--color-bg-base) / <alpha-value>)",
          primary: "rgb(var(--color-bg-primary) / <alpha-value>)",
          secondary: "rgb(var(--color-bg-secondary) / <alpha-value>)",
          tertiary: "rgb(var(--color-bg-tertiary) / <alpha-value>)",
          elevated: "rgb(var(--color-bg-elevated) / <alpha-value>)",
          hover: "rgb(var(--color-bg-hover) / <alpha-value>)",
        },
        border: {
          DEFAULT: "rgb(var(--color-border-default) / <alpha-value>)",
          subtle: "rgb(var(--color-border-subtle) / <alpha-value>)",
          strong: "rgb(var(--color-border-strong) / <alpha-value>)",
          focus: "rgb(var(--color-border-focus) / <alpha-value>)",
        },
        brand: {
          DEFAULT: "rgb(var(--color-brand) / <alpha-value>)",
          50: "#F3EFFF",
          100: "#E5DEFF",
          200: "rgb(var(--color-brand-200) / <alpha-value>)",
          300: "rgb(var(--color-brand-300) / <alpha-value>)",
          400: "#9275FF",
          500: "#7C5CFF",
          600: "#6545E8",
          700: "#5132C4",
          800: "#3F2599",
          900: "#2B1870",
        },
        accent: {
          purple: "#7C5CFF",
          "purple-light": "#9B82FF",
          "purple-dark": "#5A3ED4",
          cyan: "#00D4FF",
          pink: "#FF5D80",
        },
        text: {
          primary: "rgb(var(--color-text-primary) / <alpha-value>)",
          secondary: "rgb(var(--color-text-secondary) / <alpha-value>)",
          muted: "rgb(var(--color-text-muted) / <alpha-value>)",
          disabled: "rgb(var(--color-text-disabled) / <alpha-value>)",
        },
        status: {
          success: "#4ADE80",
          "success-bg": "rgba(74,222,128,0.1)",
          warning: "#FBBF24",
          "warning-bg": "rgba(251,191,36,0.1)",
          error: "#F87171",
          "error-bg": "rgba(248,113,113,0.1)",
          info: "#60A5FA",
          "info-bg": "rgba(96,165,250,0.1)",
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        "2xs": ["11px", { lineHeight: "1.4" }],
        xs: ["12px", { lineHeight: "1.5" }],
        sm: ["13px", { lineHeight: "1.5" }],
        base: ["14px", { lineHeight: "1.55" }],
        md: ["15px", { lineHeight: "1.55" }],
        lg: ["17px", { lineHeight: "1.4" }],
        xl: ["20px", { lineHeight: "1.3" }],
        "2xl": ["24px", { lineHeight: "1.25", letterSpacing: "-0.01em" }],
        "3xl": ["30px", { lineHeight: "1.2", letterSpacing: "-0.02em" }],
        "4xl": ["38px", { lineHeight: "1.15", letterSpacing: "-0.025em" }],
      },
      borderRadius: {
        none: "0",
        sm: "6px",
        DEFAULT: "8px",
        md: "10px",
        lg: "14px",
        xl: "18px",
        "2xl": "24px",
        pill: "9999px",
      },
      boxShadow: {
        xs: "0 1px 2px rgba(0,0,0,0.3)",
        sm: "0 2px 6px rgba(0,0,0,0.35)",
        md: "0 6px 20px rgba(0,0,0,0.45)",
        lg: "0 18px 48px rgba(0,0,0,0.55)",
        "glow-brand": "0 0 0 1px rgba(124,92,255,0.35), 0 8px 28px rgba(124,92,255,0.3)",
        "glow-cyan": "0 0 0 1px rgba(0,212,255,0.3), 0 8px 28px rgba(0,212,255,0.25)",
        "inner-border": "inset 0 0 0 1px rgba(255,255,255,0.06)",
      },
      transitionTimingFunction: {
        "out-expo": "cubic-bezier(0.22, 1, 0.36, 1)",
        "in-out-soft": "cubic-bezier(0.4, 0, 0.2, 1)",
      },
      transitionDuration: {
        120: "120ms",
        180: "180ms",
        240: "240ms",
        320: "320ms",
      },
      keyframes: {
        "fade-in": {
          from: { opacity: "0", transform: "translateY(4px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-glow": {
          "0%,100%": { boxShadow: "0 0 0 0 rgba(124,92,255,0.35)" },
          "50%": { boxShadow: "0 0 0 6px rgba(124,92,255,0)" },
        },
      },
      animation: {
        "fade-in": "fade-in 240ms cubic-bezier(0.22, 1, 0.36, 1) both",
        "pulse-glow": "pulse-glow 1.8s ease-out infinite",
      },
    },
  },
  plugins: [],
};
