import type { EditorBackendApi } from "../editorBackend";
import {
  detectPage,
  loadEditorPage,
  ocrPage,
  patchEditorTextLayer,
  processBlock,
  reinpaintPage,
  renderPreviewPage,
  retypesetPage,
  runPageActionWithOptionalMask,
  saveProjectJson,
  setEditorLayerVisibility,
  translatePage,
  updateBrushRegion,
  updateMaskRegion,
  updateReinpaintRegion,
  updateRecoveryRegion,
  healInpaintRegion,
  writeHealingMask,
  writeMaskFromPng,
} from "../tauri";

export const tauriEditorBackend: EditorBackendApi = {
  saveProjectJson,
  loadEditorPage,
  patchEditorTextLayer,
  setEditorLayerVisibility,
  updateMaskRegion,
  updateBrushRegion,
  updateRecoveryRegion,
  updateReinpaintRegion,
  writeMaskFromPng,
  writeHealingMask,
  healInpaintRegion,
  renderPreviewPage,
  runPageActionWithOptionalMask,
  retypesetPage,
  detectPage,
  ocrPage,
  translatePage,
  reinpaintPage,
  processBlock,
};
