"""Fail-closed reader for page analysis generated by the normal pipeline."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _miss(reason: str) -> dict[str, Any]:
    return {"status": "miss", "reason": reason, "pages": {}}


def cached_content_lineage(pages: dict[str, dict[str, Any]]) -> tuple[str, str] | None:
    """Return the original content identity, not the latest render execution."""
    identities = {
        (item["record"]["run_id"], item["coverage"].run_id,
         item["coverage"].origin_execution_id)
        for item in pages.values()
    }
    if len(identities) != 1:
        return None
    record_run, coverage_run, origin_execution = identities.pop()
    if record_run != coverage_run or not origin_execution:
        return None
    return record_run, origin_execution


def _within(root: Path, relative: str) -> Path:
    candidate = (root / relative).resolve()
    if not candidate.is_relative_to(root.resolve()) or candidate == root.resolve():
        raise ValueError("artifact_path_outside_work_dir")
    return candidate


def read_verified_chapter_analysis(
    work_dir: Path,
    *,
    source_tree_sha256: str,
    page_source_sha256s: dict[str, str],
    visual_config_sha256: str,
) -> dict[str, Any]:
    """Read all pages only when source, visual settings and artifacts agree.

    A miss is explicit and never supplies partially verified page data.
    """
    from integration_v1.contracts import AnalysisRecord
    from ownership.coverage import PageCoverageResult
    from vision_runtime.stage_cache import load_pre_ocr_stage

    index_path = work_dir / "vision" / "index.json"
    if not index_path.is_file():
        return _miss("index_missing")
    try:
        index = json.loads(index_path.read_bytes())
        if index.get("schema") != "traduzai.vision-chapter-analysis-index.v1":
            return _miss("index_version_changed")
        if index.get("source_tree_sha256") != source_tree_sha256:
            return _miss("source_tree_changed")
        entries = index.get("pages")
        if not isinstance(entries, list) or len(entries) != len(page_source_sha256s):
            return _miss("page_set_changed")
        result: dict[str, dict[str, Any]] = {}
        for entry in entries:
            page_id = entry.get("page_id")
            if page_id not in page_source_sha256s or page_id in result:
                return _miss("page_set_changed")
            path = _within(work_dir, entry["analysis_record_ref"])
            blob = path.read_bytes()
            if _sha256(blob) != entry.get("analysis_record_file_sha256"):
                return _miss("analysis_record_file_changed")
            record = json.loads(blob)
            claimed = record.pop("analysis_record_sha256", None)
            rebuilt = AnalysisRecord.build(record)
            if claimed != rebuilt.analysis_record_sha256 or claimed != entry.get("analysis_record_sha256"):
                return _miss("analysis_record_identity_changed")
            record = rebuilt.to_dict()
            if record.get("page_id") != page_id or record.get("source_sha256") != page_source_sha256s[page_id]:
                return _miss("page_source_changed")
            if record.get("analysis_config_sha256") != visual_config_sha256:
                return _miss("visual_config_changed")
            if record.get("status") != "complete" or record.get("publishable") is not False:
                return _miss("analysis_record_state_changed")
            artifacts = record.get("artifact_refs")
            if not isinstance(artifacts, list):
                return _miss("artifact_list_missing")
            verified: dict[str, Path] = {}
            for ref in artifacts:
                kind = ref["kind"]
                artifact_path = _within(work_dir, ref["path"])
                if kind in verified or _sha256(artifact_path.read_bytes()) != ref.get("sha256"):
                    return _miss("artifact_changed")
                verified[kind] = artifact_path
            coverage_path = verified.get("vision_coverage_result")
            if coverage_path is None:
                return _miss("coverage_missing")
            coverage = PageCoverageResult.from_canonical_json_bytes(coverage_path.read_bytes())
            if coverage.ledger.sha256 != entry.get("coverage_ledger_sha256"):
                return _miss("coverage_ledger_changed")
            stage_paths = []
            for suffix in ("json", "npz"):
                ref = entry.get(f"pre_ocr_{suffix}_ref")
                if not isinstance(ref, str):
                    return _miss("pre_ocr_stage_missing")
                stage_path = _within(work_dir, ref)
                if _sha256(stage_path.read_bytes()) != entry.get(f"pre_ocr_{suffix}_sha256"):
                    return _miss("pre_ocr_stage_changed")
                stage_paths.append(stage_path)
            stage = load_pre_ocr_stage(
                *stage_paths,
                page_id=page_id,
                source_file_sha256=record["source_sha256"],
                page_pixel_sha256=coverage.page_source_sha256,
                visual_config_sha256=visual_config_sha256,
            )
            result[page_id] = {
                "record": record, "coverage": coverage, "artifacts": verified,
                "stage": stage, "stage_paths": tuple(stage_paths),
            }
        if set(result) != set(page_source_sha256s):
            return _miss("page_set_changed")
        return {"status": "hit", "reason": None, "pages": result}
    except Exception as exc:
        return _miss(f"index_or_artifact_invalid:{type(exc).__name__}")
